//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbsence
    {
        public int AbsenceID { get; set; }
        public Nullable<System.DateTime> AbsenceStart { get; set; }
        public Nullable<System.DateTime> AbsenceEnd { get; set; }
        public string Reason { get; set; }
        public Nullable<int> EmployerID { get; set; }
    
        public virtual tblEmployer tblEmployer { get; set; }
    }
}
